Feature/devise
rjtt17/books_app pull request #3
Opened 2020-11-17 13:50 UTC by rjtt17

deviseを使ってユーザー認証を実装

2020-11-22 05:18 UTC, komagata requested changes

2020-11-22 05:18 UTC, komagata commented on Gemfile
> +  gem "rubocop-rails", require: false
rubocop-railsが二回読み込まれているようです。

2020-11-22 05:18 UTC, komagata commented on app/assets/stylesheets/users.scss
> +// Place all the styles related to the Users controller here.
不要なファイルは削除してください〜

2020-11-22 05:18 UTC, komagata commented on app/helpers/users_helper.rb
> +module UsersHelper
実装のないHelperは不要なので削除してください〜

2020-11-22 05:18 UTC, komagata commented on app/views/books/index.html.erb
> +<%= link_to t('button.user_index'), users_path %>
最終行に改行が無いようです。エディターの設定で自動で改行が入るようにできるので調べてみてください。

2020-11-22 05:18 UTC, komagata commented on test/models/user_test.rb
> +# frozen_string_literal: true
動かないテストは不要なので削除しちゃってください〜

2020-11-22 05:18 UTC, komagata commented on test/fixtures/users.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
使わないfixtureも削除してください〜

2020-11-24 13:22 UTC, rjtt17 commented on Gemfile
> +  gem "rubocop-rails", require: false
ご確認ありがとうございます。
rubocop-railsを1行削除しました〜

2020-11-24 13:22 UTC, rjtt17 commented on app/assets/stylesheets/users.scss
> +// Place all the styles related to the Users controller here.
ご確認ありがとうございます。
不要なファイルを削除しました〜

2020-11-24 13:23 UTC, rjtt17 commented on app/helpers/users_helper.rb
> +module UsersHelper
ご確認ありがとうございます。
不要なファイルを削除しました〜

2020-11-24 13:23 UTC, rjtt17 commented on app/views/books/index.html.erb
> +<%= link_to t('button.user_index'), users_path %>
ご確認ありがとうございます。
Vs Codeで保存時に自動改行が入る設定に致しました〜

2020-11-24 13:24 UTC, rjtt17 commented on test/models/user_test.rb
> +# frozen_string_literal: true
ご確認ありがとうございます。
不要なファイルを削除しました〜

2020-11-24 13:24 UTC, rjtt17 commented on test/fixtures/users.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
ご確認ありがとうございます。
不要なファイルを削除しました〜

2020-11-25 06:34 UTC, komagata requested changes

2020-11-25 06:34 UTC, komagata commented on config/locales/ja.yml
> +          has_many: "%{record}が存在しているので削除できません"
```suggestion
          has_many: "%{record}が存在しているので削除できません"
```

2020-11-25 06:34 UTC, komagata commented on config/locales/models/ja.yml
> +        biograpy: 自己紹介文
最終行に改行が無いようです。
PRを出すときはローカルで確認していたとしてもGitHub上で確認するようにしてみてください〜

2020-11-27 14:53 UTC, rjtt17 commented on config/locales/ja.yml
> +          has_many: "%{record}が存在しているので削除できません"
ご確認ありがとうございます。
こちらの不要なスペースを削除致しました〜

2020-11-27 14:56 UTC, rjtt17 commented on config/locales/models/ja.yml
> +        biograpy: 自己紹介文
ご確認ありがとうございます。
最終行に改行を入れました〜
PRの際は、GitHub上でも確認するように致します。

2020-11-30 01:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-30 13:20 UTC, merged